app/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from core.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('users/', include('user.urls')),
    path('posts/', include('posts.urls'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

app/posts/urls.py
"""
URLs mapping post app.
"""
from django.urls import path

from posts import views


urlpatterns = [
    path('create/', views.PostCreateView.as_view(), name='post_create'),
    path('delete/<int:pk>/', views.PostDeleteView.as_view(), name='post_delete'),
    path('update/<int:pk>/', views.PostUpdateView.as_view(), name='post_update'),
    path('detail/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('toggle-like/<int:pk>/', views.ToggleLikeView.as_view(), name='toggle_like'),
    path('user_post_list/', views.UserPostView.as_view(), name='user_post_list'),
    path('<int:post_pk>/create_comment/', views.CommentCreateView.as_view(), name='comment_create'),
    path('<int:post_pk>/update_comment/<int:comment_pk>/', views.CommentUpdateView.as_view(), name='comment_update'),
    path('<int:post_pk>/delete_comment/<int:comment_pk>/', views.CommentDeleteView.as_view(), name='comment_delete'),
]

app/user/urls.py
"""
URL mapping for user app.
"""
from django.urls import path, reverse_lazy

from django.contrib.auth import views as auth_views

from user import views


urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('profile/', views.UserProfile.as_view(), name='profile'),
    path('password_change/', auth_views.PasswordChangeView.as_view(
        template_name='registration/password_change.html',
        success_url=reverse_lazy('password_change_done')),
        name='password_change'
    ),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='password_change_done.html'),
        name='password_change_done'
    ),
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='registration/password_reset.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

app/core/models.py
"""
Database models.
"""
from django.db import models
from django.utils.text import slugify

from django.contrib.auth.models import User

from django.urls import reverse


class UserProfile(models.Model):
    """Model for user profile."""
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='userprofile')
    photo = models.ImageField(upload_to='avatars/', blank=True, null=True)

    def __str__(self):
        return self.user.username


class Post(models.Model):
    """Model for post."""
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post')
    image = models.ImageField(upload_to='images/%y/%m/%d')
    caption = models.TextField(blank=True)
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        """Get and return absolute URL for post."""
        return reverse('post_detail', args=[str(self.pk)])

    def __str__(self):
        return self.title

    # def total_likes(self):
    #     """Get and return a count of all likes for post."""
    #     return self.likes.count


class Like(models.Model):
    """Model for likes system."""
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, related_name='likes', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'post')


class Comment(models.Model):
    """Model for comment system."""
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    content = models.TextField()

    def __str__(self):
        return f"Comment by {self.user.username} on {self.post.title}"

app/posts/forms.py
"""
Forms for post app.
"""
from django import forms

from core.models import Post, Comment


class PostForm(forms.ModelForm):
    """Form for creating and updating posts."""

    class Meta:
        model = Post
        fields = ['title', 'caption', 'image']


class CommentForm(forms.ModelForm):
    """Form for creating comments."""

    class Meta:
        model = Comment
        fields = ['content']

app/core/views.py
"""
Views for core app.
"""
from django.db.models import Count, Case, When, IntegerField
from django.views.generic import ListView

from core.models import Post


class IndexView(ListView):
    """View for index site displaying all posts."""
    model = Post
    template_name = 'index.html'
    context_object_name = 'posts'
    queryset = Post.objects.all().order_by('-created')

    def get_queryset(self):
        user = self.request.user
        queryset = Post.objects.all().select_related('user').prefetch_related(
            'comment_set__user'
        ).annotate(likes_count=Count('likes')).order_by('-created')
        if user.is_authenticated:
            queryset = queryset.annotate(
                liked=Count(Case(When(likes__user=user, then=1),
                                 defaul=0, output_field=IntegerField()))
            )

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        for post in context['posts']:
            post.full_url = self.request.build_absolute_uri(post.get_absolute_url())
        return context

app/posts/views.py
"""
Views for posts app.
"""
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import edit, DetailView, ListView

from django.views import View
from django.urls import reverse_lazy, reverse

from posts.forms import PostForm, CommentForm
from core.models import Post, Like, Comment


class UserPostView(ListView):
    """View for user posts."""
    model = Post
    template_name = 'index.html'
    context_object_name = 'posts'

    def get_queryset(self):
        """Queryset displaying only logged user posts."""
        return (Post.objects.filter(user=self.request.user)
                .select_related('user').order_by('-created'))


class PostCreateView(edit.CreateView):
    """View for create posts."""
    model = Post
    form_class = PostForm
    template_name = 'post/post_create.html'
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class PostDeleteView(edit.DeleteView):
    """View for delete posts."""
    model = Post
    template_name = 'post/post_confirm_delete.html'
    success_url = reverse_lazy('index')

    def get_queryset(self):
        """Return queryset listed to user"""
        return Post.objects.filter(user=self.request.user)


class PostUpdateView(edit.UpdateView):
    """View for update posts."""
    model = Post
    form_class = PostForm
    template_name = 'post/post_create.html'
    success_url = reverse_lazy('index')

    def get_queryset(self):
        """Return queryset listed to user"""
        return Post.objects.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['editing'] = True
        return context


class PostDetailView(DetailView):
    """View for detail post."""
    model = Post
    template_name = 'post/post_details.html'
    context_object_name = 'post'

    def get_queryset(self):
        return Post.objects.select_related('user').prefetch_related('likes', 'comment_set__user')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = self.get_object()
        user = self.request.user
        context['comments'] = (Comment.objects.filter(post=post).select_related('user')
                               .order_by('-created'))
        context['likes_count'] = post.likes.count()
        context['liked'] = post.likes.filter(user=user).exists() if user.is_authenticated else False
        return context


@method_decorator(login_required, name='dispatch')
class ToggleLikeView(View):
    """View to toggle the like status of a post."""

    def handle_like(self, request, post):
        """Helper method to handle like/unlike logic."""
        if Like.objects.filter(user=request.user, post=post).exists():
            Like.objects.filter(user=request.user, post=post).delete()
            return False
        else:
            Like.objects.create(user=request.user, post=post)
            return True

    def post(self, request, *args, **kwargs):
        """Handle POST request to like or unlike a post."""
        post = get_object_or_404(Post, pk=kwargs.get('pk'))
        liked = self.handle_like(request, post)
        return JsonResponse({'liked': liked, 'total_likes': post.likes.count()})

    def delete(self, request, *args, **kwargs):
        """Handle DELETE request to unlike a post."""
        post = get_object_or_404(Post, pk=kwargs.get('pk'))
        liked = self.handle_like(request, post)
        return JsonResponse({'liked': liked, 'total_likes': post.likes.count()})

    def get(self, request, *args, **kwargs):
        """Handle GET request to get the total number of likes for a post."""
        post = get_object_or_404(Post, pk=kwargs.get('pk'))
        return JsonResponse({'total_likes': post.likes.count})

class CommentCreateView(edit.CreateView):
    """View for create comments."""
    model = Comment
    form_class = CommentForm
    template_name = 'comment/comment_create.html'

    def get_success_url(self):
        return reverse('post_detail', kwargs={'pk': self.kwargs['post_pk']})

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.post_id = self.kwargs['post_pk']
        return super().form_valid(form)


class CommentUpdateView(edit.UpdateView):
    """View for update comments."""
    model = Comment
    form_class = CommentForm
    template_name = 'comment/comment_create.html'

    def get_success_url(self):
        return reverse('post_detail', kwargs={'pk': self.kwargs['post_pk']})

    def get_object(self, queryset=None):
        comment_id = self.kwargs.get('comment_pk')
        return Comment.objects.get(pk=comment_id)

    def get_queryset(self):
        return Comment.objects.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['editing'] = True
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class CommentDeleteView(edit.DeleteView):
    """View for delete posts."""
    model = Comment
    template_name = 'comment/comment_delete.html'

    def get_success_url(self):
        return reverse_lazy('post_detail', kwargs={'pk': self.kwargs['post_pk']})

    def get_object(self, queryset=None):
        comment_id = self.kwargs.get('comment_pk')
        return Comment.objects.get(pk=comment_id)

    def get_queryset(self):
        return Comment.objects.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = get_object_or_404(Post, pk=self.kwargs['post_pk'])
        context['post'] = post
        return context

app/core/templates/post/post_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Delete Post{% endblock %}

{% block content %}
<div class="container mx-auto mt-10 max-w-sm text-center">
    <h2 class="text-2xl font-bold mb-6">Delete Post</h2>
    <p>Are you sure you want to delete this post?</p>
    <div class="mt-4">
        <button type="button" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded" data-toggle="modal" data-target="#confirmDeleteModal">
            Yes, delete
        </button>
        <a href="{{ request.META.HTTP_REFERER }}" class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded">
            Cancel
        </a>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="confirmDeleteModal" tabindex="-1" role="dialog" aria-labelledby="confirmDeleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="confirmDeleteModalLabel">Confirm Delete</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete this post?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <form method="post" action="{% url 'post_delete' post.id %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Delete</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block extra_js %}
<script>
    $('#confirmDeleteModal').on('shown.bs.modal', function () {
        // Focus on the cancel button when modal is shown
        $(this).find('[data-dismiss="modal"]').focus();
    });
</script>
{% endblock %}

app/core/templates/post/post_create.html
{% extends 'base.html' %}

{% if editing %}
    Edit Post
{% else %}
    Create Post
{% endif %}

{% block content %}
<div class="container mx-auto mt-10 max-w-lg">
    <h2 class="text-2xl font-bold mb-6 text-center">
        {% if editing %}
            Edit Post
        {% else %}
            Create Post
        {% endif %}
    </h2>
    <form id="postForm" method="post" enctype="multipart/form-data" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="mb-4">
            <label for="id_title" class="block text-gray-700 text-sm font-bold mb-2">Title:</label>
            {{ form.title }}
        </div>
        <div class="mb-4">
            <label for="id_caption" class="block text-gray-700 text-sm font-bold mb-2">Caption:</label>
            {{ form.caption }}
        </div>
        <div class="mb-4 flex items-center">
            <label for="id_image" class="block text-gray-700 text-sm font-bold mb-2">Image:</label>
            {% if editing and form.instance.image %}
                <img id="preview" src="{{ form.instance.image.url }}" alt="Current Image" class="ml-4 w-20 h-20 object-cover rounded">
            {% else %}
                <img id="preview" src="#" alt="Image preview" style="display: none;">
            {% endif %}
        </div>
        <div class="mb-4">
            <label class="custom-file-upload">
                Choose File
                <input type="file" id="id_image" name="image" onchange="previewImage(event)">
            </label>
        </div>
        <div class="flex items-center justify-center space-x-4 mt-8">
            <button type="button" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" onclick="submitPostForm(event)">
                {% if editing %}
                    Update Post
                {% else %}
                    Create Post
                {% endif %}
            </button>
            <button type="button" class="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded" onclick="location.href='{% url 'index' %}'">
                Cancel
            </button>
        </div>
    </form>
</div>

<!-- Modal -->
<div class="modal fade" id="confirmationModal" tabindex="-1" role="dialog" aria-labelledby="confirmationModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="confirmationModalLabel">Confirm Image</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <img id="modalPreview" src="#" alt="Image preview" class="img-fluid">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" onclick="acceptImage()">Yes, use this image</button>
            </div>
        </div>
    </div>
</div>

<script>
    let imageAccepted = {% if editing and form.instance.image %}true{% else %}false{% endif %};

    function previewImage(event) {
        var reader = new FileReader();
        reader.onload = function() {
            var output = document.getElementById('modalPreview');
            output.src = reader.result;
            $('#confirmationModal').modal('show');
        }
        reader.readAsDataURL(event.target.files[0]);
    }

    function acceptImage() {
        imageAccepted = true;
        var reader = new FileReader();
        reader.onload = function() {
            var output = document.getElementById('preview');
            output.src = reader.result;
            output.style.display = 'block';
        }
        reader.readAsDataURL(document.getElementById('id_image').files[0]);
        $('#confirmationModal').modal('hide');
    }

    function submitPostForm(event) {
        if (!imageAccepted) {
            alert('Please confirm the image first.');
            return;
        }
        document.getElementById('postForm').submit();
    }
</script>
{% endblock %}

app/core/templates/post/post_details.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Post Detail{% endblock %}

{% block content %}
<div class="container mx-auto mt-10">
    <div class="bg-white shadow-md rounded p-4">
        <div class="flex items-center mb-4">
            {% if post.user.userprofile.photo %}
                <img src="{{ post.user.userprofile.photo.url }}" alt="{{ post.user.username }}" class="w-10 h-10 rounded-full mr-4">
            {% else %}
                <img src="/media/avatars/default-avatar.png" alt="{{ post.user.username }}" class="w-10 h-10 rounded-full mr-4">
            {% endif %}
            <span class="font-semibold">{{ post.user.username }}</span>
            {% if user.is_authenticated and user == post.user %}
                <div class="ml-auto">
                    <a href="{% url 'post_update' post.id %}" class="text-blue-500 mr-2">
                        <i class="fas fa-edit"></i> Edit
                    </a>
                    <a href="{% url 'post_delete' post.id %}" class="text-red-500" onclick="return confirm('Are you sure you want to delete this post?');">
                        <i class="fas fa-trash-alt"></i> Delete
                    </a>
                </div>
            {% endif %}
        </div>
        <h3 class="text-lg font-semibold mb-2">{{ post.title }}</h3>
        <img src="{{ post.image.url }}" alt="{{ post.title }}" class="w-full h-auto object-cover mb-4 rounded">
        <p class="text-gray-700 mb-2">{{ post.caption }}</p>
        <div class="icon-container mt-4 flex space-x-4">
            <button class="like-button cursor-pointer focus:outline-none" data-post-id="{{ post.id }}" data-liked="{{ liked }}">
                <img src="{% static 'images/like.png' %}" alt="Like" class="w-6 h-6">
                <span class="ml-1 likes-count" id="likes-count-{{ post.id }}">{{ likes_count }}</span>
            </button>
            <a href="{% url 'post_detail' post.id %}#comments" class="cursor-pointer">
                <img src="{% static 'images/comment.png' %}" alt="Comment" class="w-6 h-6">
            </a>
            <button onclick="copyToClipboard('{{ post.full_url }}')" class="bg-transparent border-none cursor-pointer">
                <img src="{% static 'images/share.png' %}" alt="Share" class="w-6 h-6">
            </button>
        </div>
    </div>

    <div id="comments" class="mt-6">
        <h3 class="text-xl font-bold mb-4">Comments</h3>
        {% if comments %}
            {% for comment in comments %}
                <div class="bg-gray-100 rounded-lg p-3 mb-3">
                    <div class="flex items-center mb-2">
                        {% if comment.user.userprofile.photo %}
                            <img src="{{ comment.user.userprofile.photo.url }}" alt="{{ comment.user.username }}" class="w-8 h-8 rounded-full mr-2">
                        {% else %}
                            <img src="/media/avatars/default-avatar.png" alt="{{ comment.user.username }}" class="w-8 h-8 rounded-full mr-2">
                        {% endif %}
                        <span class="font-semibold">{{ comment.user.username }}</span>
                        <span class="text-gray-500 ml-2">{{ comment.created }}</span>
                        {% if user.is_authenticated and user == comment.user %}
                            <div class="ml-auto">
                                <a href="{% url 'comment_update' post.pk comment.id %}" class="text-blue-500 mr-2">
                                    <i class="fas fa-edit"></i> Edit
                                </a>
                                <a href="{% url 'comment_delete' post.pk comment.id %}" class="text-red-500">
                                    <i class="fas fa-trash-alt"></i> Delete
                                </a>
                            </div>
                        {% endif %}
                    </div>
                    <p>{{ comment.content }}</p>
                </div>
            {% endfor %}
        {% else %}
            <p>No comments yet.</p>
        {% endif %}

        {% if user.is_authenticated %}
            <form method="post" action="{% url 'comment_create' post.pk %}">
                {% csrf_token %}
                <div class="mt-4">
                    <label for="id_content" class="block text-sm font-medium text-gray-700">Add a comment:</label>
                    <textarea name="content" id="id_content" rows="3" class="form-textarea mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"></textarea>
                </div>
                <div class="mt-4">
                    <button type="submit" class="inline-flex items-center px-4 py-2 border border-transparent text-base font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                        Add Comment
                    </button>
                </div>
            </form>
        {% else %}
            <p class="mt-4"><a href="{% url 'login' %}" class="text-indigo-600 hover:underline">Log in</a> to add a comment.</p>
        {% endif %}
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        // Event listener for like button click
        const likeButton = document.querySelector('.like-button');
        if (likeButton) {
            likeButton.addEventListener('click', () => {
                const postId = likeButton.dataset.postId;
                const liked = likeButton.dataset.liked === 'true';
                toggleLike(postId, liked);
            });
        }
    });

    function toggleLike(postId, liked) {
        const url = `/posts/toggle-like/${postId}/`;
        const method = liked ? 'DELETE' : 'POST';
        fetch(url, {
            method: method,
            headers: {
                'X-Requested-With': 'XMLHttpRequest',
                'X-CSRFToken': getCookie('csrftoken'),
            }
        })
        .then(response => response.json())
        .then(data => {
            updateLikesCount(postId, data.total_likes);
            const likeButton = document.querySelector(`.like-button[data-post-id="${postId}"]`);
            if (likeButton) {
                likeButton.dataset.liked = data.liked;
            }
        })
        .catch(error => console.error('Error toggling like:', error));
    }

    function updateLikesCount(postId, likesCount) {
        const likesCountSpan = document.querySelector(`#likes-count-${postId}`);
        if (likesCountSpan) {
            likesCountSpan.innerText = likesCount;
        }
    }

    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    function copyToClipboard(text) {
        navigator.clipboard.writeText(text).then(function() {
            alert('Link copied to clipboard');
        }, function(err) {
            console.error('Could not copy text: ', err);
        });
    }
</script>
{% endblock %}